language: java
before_install:
  - sudo apt-get update -qq
  - if [ $(uname -m) = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
  - wget http://dl.google.com/android/android-sdk_r21.0.1-linux.tgz
  - tar zxf android-sdk_r21.0.1-linux.tgz
  - export ANDROID_HOME=$(pwd)/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - echo y | android update sdk --all --filter platform-tools,android-19 --no-ui --force
  - android update project -p .
script:
  - ant clean debug
