language: android
android:
  components:
    - build-tools-19.1.0
    - android-19
    - extra-android-support
  licenses:
    - android-sdk-license-*
before_install:
  - echo $ANDROID_HOME
  - ln -sf $ANDROID_HOME/extras/android/support/v7/appcompat appcompat
  - android update project -p . --subprojects --target android-19
script: ant clean debug
